[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
name = "backend"
crate_type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.19.0"